server:
  port: 8081
  servlet:
    context-path: /api/catalogue

spring:
  application:
    name: "Product Service"
  data:
    mongodb:
      uri: mongodb://scalerkart_ecom_product:scalerkart_ecom_product@104.154.48.212:27017
      host: 104.154.48.212
      port: 27017
      database: scalerkart_ecom_product
      auto-index-creation: true
  mvc:
    trailing-slash-match: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
