global:
  namespace: scalerkart
  imageRegistry: us-central1-docker.pkg.dev/scalerkart-453310/scalerkart-artifact-registry

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        database: "scalerkart_ecom"
        username: "scalerkart_user"
        password: "securepassword"
  persistence:
    size: 1Gi
    storageClass: "standard"

mongodb:
  enabled: true
  auth:
    rootPassword: "securepassword"
  persistence:
    size: 5Gi
    storageClass: "standard"

services:
  apiGateway:
    image: api-gateway
    tag: latest
    serviceType: LoadBalancer
    staticIP: 34.123.134.182
    resources:
      requests:
        cpu: "300m"
        memory: "200Mi"
      limits:
        cpu: "600m"
        memory: "400Mi"

  authentication:
    image: authentication
    tag: latest
    dbName: "auth"
    port: 8080
    # ... similar structure for other services

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5