apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-postgresql
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  postgresql-username: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  postgresql-password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}