server:
  port: 8080
  servlet:
    context-path: /api/authentication

spring:
  application:
    name: "authentication service"
  datasource:
    url: "jdbc:h2:file:~/h2/scalerkart_ecom_auth;DB_CLOSE_ON_EXIT=TRUE"
    username: "scalerkart_ecom_auth"
    password: "scalerkart_ecom_auth"
    driverClassName: "org.h2.Driver"
  jpa:
#    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
        use_sql_comments: true
        show-sql: false
        format_sql: false
    generate-ddl: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          description:
            sql:
              BasicBinder: TRACE

jwt:
  secret: "scalerkart-2024-2025-ecommerce-project-token-secret-for-ashesh"
  expiration: 86400
  refreshExpiration: 172800